# 选择一个体积小的镜像 (~5MB)
FROM node:16-alpine

WORKDIR /code

# 单独分离 package.json，是为了安装依赖可最大限度利用缓存
ADD package.json pnpm-lock.yaml /code/
# 此时，yarn 可以利用缓存，如果 yarn.lock 内容没有变化，则不会重新依赖安装
RUN npx pnpm install

ADD . /code

RUN npm run build

# 启动 Node Server
CMD npm run prod

EXPOSE 9009